- profile_id: org.momentum.mez.profile.minimal-mvp
  latest: 0.4.44
- profile_id: org.momentum.mez.profile.digital-native-free-zone
  latest: 0.4.44
- profile_id: org.momentum.mez.profile.digital-financial-center
  latest: 0.4.44
- profile_id: org.momentum.mez.profile.charter-city
  latest: 0.4.44
- profile_id: org.momentum.mez.profile.trade-playbook
  latest: 0.4.44
