# Profiles registry

- profile_id: org.momentum.msez.profile.minimal-mvp
  latest: 0.2.0

- profile_id: org.momentum.msez.profile.digital-native-free-zone
  latest: 0.2.0

- profile_id: org.momentum.msez.profile.digital-financial-center
  latest: 0.2.0

- profile_id: org.momentum.msez.profile.charter-city
  latest: 0.2.0
