-- Tax Collection Pipeline Persistence — Tax Events
--
-- Stores tax events generated by the tax collection pipeline. These are
-- SEZ-Stack-owned records representing the jurisdictional tax awareness
-- applied to Mass fiscal operations, NOT Mass fiscal CRUD.
--
-- See CLAUDE.md Section II and P1-009 in the defect inventory.

CREATE TABLE IF NOT EXISTS tax_events (
    id                  UUID PRIMARY KEY,
    entity_id           UUID NOT NULL,
    event_type          VARCHAR(100) NOT NULL,
    tax_category        VARCHAR(100) NOT NULL,
    jurisdiction_id     VARCHAR(10) NOT NULL,
    gross_amount        VARCHAR(50) NOT NULL,
    withholding_amount  VARCHAR(50) NOT NULL,
    net_amount          VARCHAR(50) NOT NULL,
    currency            VARCHAR(5) NOT NULL,
    tax_year            VARCHAR(20) NOT NULL,
    ntn                 VARCHAR(7),
    filer_status        VARCHAR(20) NOT NULL DEFAULT 'non_filer',
    statutory_section   VARCHAR(255),
    withholding_executed BOOLEAN NOT NULL DEFAULT false,
    mass_payment_id     UUID,
    rules_applied       INTEGER NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT valid_filer_status CHECK (
        filer_status IN ('filer', 'late_filer', 'non_filer')
    )
);

CREATE INDEX IF NOT EXISTS idx_tax_events_entity ON tax_events(entity_id);
CREATE INDEX IF NOT EXISTS idx_tax_events_jurisdiction ON tax_events(jurisdiction_id);
CREATE INDEX IF NOT EXISTS idx_tax_events_tax_year ON tax_events(tax_year);
CREATE INDEX IF NOT EXISTS idx_tax_events_entity_jurisdiction ON tax_events(entity_id, jurisdiction_id, tax_year);
CREATE INDEX IF NOT EXISTS idx_tax_events_created ON tax_events(created_at);
